server:
  port: 8080
  servlet:
    context-path: /wechat
  #tomcat:
  #max-http-post-size: -1
  max-http-header-size: 104857600
logging:
  config: classpath:logback-spring.xml
spring:
  profiles:
    active: "@profiles.active@"
  datasource:
    name: development
    url: jdbc:mysql://127.0.0.1:3306/music?useSSL=false&useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: 12345
        reset-enable: false
    http:
      multipart:
        enabled: true
        max-file-size: 30MB
        max-request-size: 1024MB


swagger:
  enabled: true


mybatis:
  mapperLocations: classpath*:mybatis/**/*.xml
  executor-type: reuse
  type-aliases-package: com.*.model
  configuration:
    map-underscore-to-camel-case: true
  redis:
    database: 3
    host: 127.0.0.1
    port: 6379
    password: Yb857617227.
    timeout: 100000
    pool:
      min-idle: 0
      max-idle: 8
      max-wait: -1
      max-active: 8

#pagehelper分页插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

#web:
#  upload-path-linux : /usr/local/portals/dev/server/apache-tomcat-8.5.23/webapps/upload/
#  upload-path-win : C:/zhouzeqiang/tomcat/apache-tomcat-9.0.14/webapps/upload/
